GET http://localhost:3030/projects

#####

POST http://localhost:3030/projects HTTP/1.1
Content-Type: application/json

{
    "title": "Progetto di prova 2",
    "description": "Un progetto per testare i progettini",
    "category": "Servizio1",
    "author": "6430239d37bb6431c8421ced",
    "file": "http://localhost:3030/file"
}

#####

PATCH http://localhost:3030/projects/6433e3dce217f41eab214f6a
Content-Type: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2FybG8iLCJzdXJuYW1lIjoiQ2FwdW96em8iLCJuaWNrbmFtZSI6IkFkbWluaXN0cmF0b3IiLCJlbWFpbCI6ImNhcmxvY2FwMDhAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiYmlydGgiOiIxOTkyLTExLTA4IiwiYXZhdGFyIjoiaHR0cDovL2xvY2FsaG9zdDozMDMwL2F2YXRhci9hdmF0YXItMTY4MTIzMzM5MDMyMC0zMS5qcGciLCJpc0FjdGl2ZSI6dHJ1ZSwiaWQiOiI2NDMwMjM5ZDM3YmI2NDMxYzg0MjFjZWQiLCJpYXQiOjE2ODIwMTQyODgsImV4cCI6MTY4MjAxNTE4OH0.tJjU6jDK1nXjwOw3lMMCqPuqamh4lrpp1UIuW_CV1Qs"

{
    "category": ["editing"]
}