GET http://localhost:3030/projects

#####

POST http://localhost:3030/projects HTTP/1.1
Content-Type: application/json

{
    "title": "Progetto di prova 2",
    "description": "Un progetto per testare i progettini",
    "category": "Servizio1",
    "author": "6430239d37bb6431c8421ced",
    "file": "http://localhost:3030/file"
}

#####

PATCH http://localhost:3030/projects/643c74e1c591d92d3996b4b9
Content-Type: application/json

{
    "status": "in attesa"
}