GET http://localhost:3030/users

#####

GET http://localhost:3030/pagination

#####

POST http://localhost:3030/users HTTP/1.1
Content-Type: application/json

{
    "name": "Gianni",
    "surname": "Capuozzo",
    "nickname": "Giannivo",
    "email": "carlocap10@gmail.com",
    "password": "carlocap23@",
    "role": "admin",
    "birth": "08-11-1992",
    "avatar": "https://ui-avatars.com/api/?name=Carlo+Capuozzo"
}

#####

PATCH http://localhost:3030/users/6430239d37bb6431c8421ced
Content-Type: application/json

{
    "role": "admin"
}

#####

DELETE http://localhost:3030/users/643024fa37bb6431c8421cff